<?=include('common/header.php');?>
<?=include('common/sidebar.php');?>
<div class="main">
    <?=include('common/topNav.php');?>
    <main class="title" style="z-index: 10">
        <div class="container-fluid">
            <div class="header">
                <h1 class="header-title">
                    Startup Metrics
                </h1>
            </div>
            <div class="row">
                <div class="col-md-12 py-5">
                    <div class="card">
                        <div class="card-body">
                            <form action="<?=base_url();?>StartupMetrics" method="get" class="inline-form">

                                <select name="year" style="width:200px; height:50px; padding:10px;">
                                    <option value="">Select Year</option>
                                    <?php
                                                              for($i=2023; $i>=2000; $i--)
                                                              {
                                                             ?>
                                    <option value="<?=$i;?>" <?php if($i==$_GET['year']){echo "selected"; }?>><?=$i;?>
                                    </option>
                                    <?php
                                                              } 
                                                            ?>
                                </select>


                                <select name="month" style="width:200px; height:50px; padding:10px;">
                                    <option value="">Select Month</option>
                                    <option value="JAN" <?php if($_GET['month']=="JAN"){echo "selected"; }?>>JAN
                                    </option>
                                    <option value="FEB" <?php if($_GET['month']=="FEB"){echo "selected"; }?>>FEB
                                    </option>
                                    <option value="MAR" <?php if($_GET['month']=="MAR"){echo "selected"; }?>>MAR
                                    </option>
                                    <option value="APR" <?php if($_GET['month']=="APR"){echo "selected"; }?>>APR
                                    </option>
                                    <option value="MAY" <?php if($_GET['month']=="MAY"){echo "selected"; }?>>MAY
                                    </option>
                                    <option value="JUN" <?php if($_GET['month']=="JUN"){echo "selected"; }?>>JUN
                                    </option>
                                    <option value="JUL" <?php if($_GET['month']=="JUL"){echo "selected"; }?>>JUL
                                    </option>
                                    <option value="AUG" <?php if($_GET['month']=="AUG"){echo "selected"; }?>>AUG
                                    </option>
                                    <option value="SEP" <?php if($_GET['month']=="SEP"){echo "selected"; }?>>SEP
                                    </option>
                                    <option value="OCT" <?php if($_GET['month']=="OCT"){echo "selected"; }?>>OCT
                                    </option>
                                    <option value="NOV" <?php if($_GET['month']=="NOV"){echo "selected"; }?>>NOV
                                    </option>
                                    <option value="DEC" <?php if($_GET['month']=="DEC"){echo "selected"; }?>>DEC
                                    </option>

                                </select>

                                <input type="submit" style="width:200px; height:50px; padding:10px;"
                                    class="btn btn-primary" value="Search" />

                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <div class="card shadow">
                        <div class="card-header text-center">
                            <img src="<?=base_url('assets/img/metrics/1.png');?>" />
                            <h4 data-toggle="tooltip"
                                title="Monthly Recurring Revenue (MRR) is the predictable total revenue generated by your business from all the active subscriptions in a particular month. ">
                                Monthly Recurring Revenue</h4>
                        </div>
                        <div class="card-body text-center">
                            <?php
                              if(isset($_GET['year']) && isset($_GET['month']))
                              {
                                $mrr = $this->db->get_where('mrr',array('month'=>$_GET['month'],'year'=>$_GET['year'],'startup_id'=>$startup->id,'status'=>1))->row();
                                echo "<h3>₹ ".number_format($mrr->mrr)."/-</h3>";
                              } 
                              else 
                              {
                                echo "NA";
                              }
                            ?>
                        </div>
                        <div class="card-footer text-center">
                            <a href="#" class="btn btn-success"
                                onclick="showAjaxModal('<?=base_url(); ?>Popup/index/add-matrics/<?=$a=1;?>')"><i
                                    class="fa fa-plus"></i></a>
                            <a href="<?=base_url();?>StartupMetrics/MRR" class="btn btn-warning">MRR List</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-3 shadow">
                    <div class="card text-center">
                        <div class="card-header text-center">
                            <img src="<?=base_url('assets/img/metrics/2.png');?>" />
                            <h4 data-toggle="tooltip"
                                title="the amount of money a business spends to get a customer to purchase its products or services.">
                                Customer Acquisition Cost</h4>
                        </div>
                        <div class="card-body">
                            <?php
                              if(isset($_GET['year']) && isset($_GET['month']))
                              {
                                $cac = $this->db->get_where('cac',array('month'=>$_GET['month'],'year'=>$_GET['year'],'startup_id'=>$startup->id,'status'=>1))->row();
                                echo "<h3>₹ ".number_format($cac->cac)."/-</h3>";
                              } 
                              else 
                              {
                                echo "NA";
                              }
                            ?>
                        </div>
                        <div class="card-footer">
                            <a href="#" class="btn btn-success"
                                onclick="showAjaxModal('<?=base_url(); ?>Popup/index/add-matrics/<?=$a=2;?>')"><i
                                    class="fa fa-plus"></i></a>
                            <a href="<?=base_url();?>StartupMetrics/CAC" class="btn btn-warning">CAC List</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="card text-center">
                        <div class="card-header text-center">
                            <img src="<?=base_url('assets/img/metrics/3.png');?>" />
                            <h4 data-toggle="tooltip"
                                title="Customer lifetime value (CLV or CLTV) is a metric that represents the total net profit a company can expect to generate from a customer throughout their entire relationship.">
                                Customer Lifetime Value</h4>
                        </div>
                        <div class="card-body">
                            <?php
                              if(isset($_GET['year']) && isset($_GET['month']))
                              {
                                $clv = $this->db->get_where('clv',array('month'=>$_GET['month'],'year'=>$_GET['year'],'startup_id'=>$startup->id,'status'=>1))->row();
                                echo "<h3>₹ ".number_format($clv->clv)."/-</h3>";
                              } 
                              else 
                              {
                                echo "NA";
                              }
                            ?>
                        </div>
                        <div class="card-footer">
                            <a href="#" class="btn btn-success"
                                onclick="showAjaxModal('<?=base_url(); ?>Popup/index/add-matrics/<?=$a=3;?>')"><i
                                    class="fa fa-plus"></i></a>
                            <a href="<?=base_url();?>StartupMetrics/CLVList" class="btn btn-warning">CLV List</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="card text-center">
                        <div class="card-header text-center">
                            <img src="<?=base_url('assets/img/metrics/4.png');?>" />
                            <h4 data-toggle="tooltip"
                                title="Gross revenue refers to the total amount of money generated by a business through its normal operations before deducting any expenses or taxes. It represents the total sales or income earned by a company from its products or services. Gross revenue is also known as gross sales, gross income, or total revenue.">
                                Gross Revenue</h4>
                        </div>
                        <div class="card-body">
                            <?php
                              if(isset($_GET['year']) && isset($_GET['month']))
                              {
                                $gross = $this->db->get_where('gross_revenue',array('month'=>$_GET['month'],'year'=>$_GET['year'],'startup_id'=>$startup->id,'status'=>1))->row();
                                echo "<h3>₹ ".number_format($gross->gross)."/-</h3>";
                              } 
                              else 
                              {
                                echo "NA";
                              }
                            ?>
                        </div>
                        <div class="card-footer">
                            <a href="#" class="btn btn-success"
                                onclick="showAjaxModal('<?=base_url(); ?>Popup/index/add-matrics/<?=$a=4;?>')"><i
                                    class="fa fa-plus"></i></a>
                            <a href="<?=base_url();?>StartupMetrics/GrossList" class="btn btn-warning">Gross Revenue
                                List</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="card text-center">
                        <div class="card-header text-center">
                            <img src="<?=base_url('assets/img/metrics/5.png');?>" />
                            <h4 data-toggle="tooltip"
                                title="Churn rate, also known as customer attrition rate, is a metric used to measure the rate at which customers or subscribers stop using a product or service over a given period of time.">
                                Churn Rate</h4>
                        </div>
                        <div class="card-body">
                            <?php
                              if(isset($_GET['year']) && isset($_GET['month']))
                              {
                                $churn_rate = $this->db->get_where('churn_rate',array('month'=>$_GET['month'],'year'=>$_GET['year'],'startup_id'=>$startup->id,'status'=>1))->row();
                                echo "<h3>".number_format($churn_rate->churn_rate)."%</h3>";
                              } 
                              else 
                              {
                                echo "NA";
                              }
                            ?>
                        </div>
                        <div class="card-footer">
                            <a href="#" class="btn btn-success"
                                onclick="showAjaxModal('<?=base_url(); ?>Popup/index/add-matrics/<?=$a=5;?>')"><i
                                    class="fa fa-plus"></i></a>
                            <a href="<?=base_url();?>StartupMetrics/ChurnRateList" class="btn btn-warning">Churn Rate
                                List</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="card text-center">
                        <div class="card-header text-center">
                            <img src="<?=base_url('assets/img/metrics/6.png');?>" />
                            <h4 data-toggle="tooltip"
                                title="Burn rate refers to the rate at which a company is spending or consuming its available cash or resources. It is typically measured on a monthly basis and represents the amount of money a company is losing or 'burning' to cover its expenses, such as salaries, rent, marketing, research and development, and other operational costs.">
                                Cash Burn </h4>
                        </div>
                        <div class="card-body">
                            <?php
                              if(isset($_GET['year']) && isset($_GET['month']))
                              {
                                $burn_rate = $this->db->get_where('burn_rate',array('month'=>$_GET['month'],'year'=>$_GET['year'],'startup_id'=>$startup->id,'status'=>1))->row();
                                echo "<h3> ₹".number_format($burn_rate->burn_rate)."/-</h3>";
                              } 
                              else 
                              {
                                echo "NA";
                              }
                            ?>
                        </div>
                        <div class="card-footer">
                            <a href="#" class="btn btn-success"
                                onclick="showAjaxModal('<?=base_url(); ?>Popup/index/add-matrics/<?=$a=6;?>')"><i
                                    class="fa fa-plus"></i></a>
                            <a href="<?=base_url();?>StartupMetrics/BurnRateList" class="btn btn-warning">Burn Rate
                                List</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="card text-center">
                        <div class="card-header text-center">
                            <img src="<?=base_url('assets/img/metrics/7.png');?>" />
                            <h4 data-toggle="tooltip"
                                title="Net revenue, also known as net sales or net sales revenue, is the total amount of revenue generated by a company after deducting any returns, discounts, and allowances. It represents the actual revenue earned by a company from its core business operations, excluding any costs or expenses associated with the production or delivery of goods or services.">
                                Net Revenue</h4>
                        </div>
                        <div class="card-body">
                            <?php
                              if(isset($_GET['year']) && isset($_GET['month']))
                              {
                                $revenue = $this->db->get_where('revenue',array('month'=>$_GET['month'],'year'=>$_GET['year'],'startup_id'=>$startup->id,'status'=>1))->row();
                                echo "<h3> ₹".number_format($revenue->revenue)."/-</h3>";
                              } 
                              else 
                              {
                                echo "NA";
                              }
                            ?>
                        </div>
                        <div class="card-footer">
                            <a href="#" class="btn btn-success"
                                onclick="showAjaxModal('<?=base_url(); ?>Popup/index/add-matrics/<?=$a=7;?>')"><i
                                    class="fa fa-plus"></i></a>
                            <a href="<?=base_url();?>StartupMetrics/RevenueList" class="btn btn-warning">Net Revenue
                                List</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="card text-center">
                        <div class="card-header text-center">
                            <img src="<?=base_url('assets/img/metrics/8.png');?>" />
                            <h4 data-toggle="tooltip"
                                title="Gross profit is the difference between revenue from sales and the direct costs associated with producing or delivering the goods or services sold. It represents the amount of money a company has left after deducting the cost of production from its total sales. ">
                                Gross Profit</h4>
                        </div>
                        <div class="card-body">
                            <?php
                              if(isset($_GET['year']) && isset($_GET['month']))
                              {
                                $gross_profit = $this->db->get_where('gross_profit',array('month'=>$_GET['month'],'year'=>$_GET['year'],'startup_id'=>$startup->id,'status'=>1))->row();
                                echo "<h3> ₹".number_format($gross_profit->gross_profit)."/-</h3>";
                              } 
                              else 
                              {
                                echo "NA";
                              }
                            ?>
                        </div>
                        <div class="card-footer">
                            <a href="#" class="btn btn-success"
                                onclick="showAjaxModal('<?=base_url(); ?>Popup/index/add-matrics/<?=$a=8;?>')"><i
                                    class="fa fa-plus"></i></a>
                            <a href="<?=base_url();?>StartupMetrics/GrossProfitList" class="btn btn-warning">Gross
                                Profit
                                List</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="card text-center">
                        <div class="card-header text-center">
                            <img src="<?=base_url('assets/img/metrics/9.png');?>" />
                            <h4 data-toggle="tooltip"
                                title="a profit from business operations (gross profit minus operating expenses) before deduction of interest and taxes.">
                                Operating Profit</h4>
                        </div>
                        <div class="card-body">
                            <?php
                              if(isset($_GET['year']) && isset($_GET['month']))
                              {
                                $operating_profit = $this->db->get_where('operating_profit',array('month'=>$_GET['month'],'year'=>$_GET['year'],'startup_id'=>$startup->id,'status'=>1))->row();
                                echo "<h3> ₹".number_format($operating_profit->operating_profit)."/-</h3>";
                              } 
                              else 
                              {
                                echo "NA";
                              }
                            ?>
                        </div>
                        <div class="card-footer">
                            <a href="#" class="btn btn-success"
                                onclick="showAjaxModal('<?=base_url(); ?>Popup/index/add-matrics/<?=$a=9;?>')"><i
                                    class="fa fa-plus"></i></a>
                            <a href="<?=base_url();?>StartupMetrics/OperatingProfitList"
                                class="btn btn-warning">Operating
                                Profit
                                List</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="card text-center">
                        <div class="card-body text-center">
                            <img src="<?=base_url('assets/img/metrics/10.png');?>" />
                            <h4>Gross Profit Margin in %</h4>
                            <?php
                              if(isset($_GET['year']) && isset($_GET['month']))
                              {
                                $gross_profit_margin = $this->db->get_where('gross_profit_margin',array('month'=>$_GET['month'],'year'=>$_GET['year'],'startup_id'=>$startup->id,'status'=>1))->row();
                                echo "<h3> ".number_format($gross_profit_margin->gpm)."%</h3>";
                              } 
                              else 
                              {
                                echo "NA";
                              }
                            ?>
                        </div>
                        <div class="card-footer">
                            <a href="#" class="btn btn-success"
                                onclick="showAjaxModal('<?=base_url(); ?>Popup/index/add-matrics/<?=$a=10;?>')"><i
                                    class="fa fa-plus"></i></a>
                            <a href="<?=base_url();?>StartupMetrics/GrossProfitMarginList" class="btn btn-warning">Gross
                                Profit Margin List</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="card text-center">
                        <div class="card-body text-center">
                            <img src="<?=base_url('assets/img/metrics/11.png');?>" />
                            <h4>Operating Profit Margin in %</h4>
                            <?php
                              if(isset($_GET['year']) && isset($_GET['month']))
                              {
                                $operating_profit = $this->db->get_where('operating_profit_margin',array('month'=>$_GET['month'],'year'=>$_GET['year'],'startup_id'=>$startup->id,'status'=>1))->row();
                                echo "<h3> ".number_format($operating_profit->opm)."</h3>";
                              } 
                              else 
                              {
                                echo "NA";
                              }
                            ?>
                        </div>
                        <div class="card-footer">
                            <a href="#" class="btn btn-success"
                                onclick="showAjaxModal('<?=base_url(); ?>Popup/index/add-matrics/<?=$a=11;?>')"><i
                                    class="fa fa-plus"></i></a>
                            <a href="<?=base_url();?>StartupMetrics/OperatingProfitMarginList"
                                class="btn btn-warning">OPM
                                List</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="card text-center">
                        <div class="card-body text-center">
                            <img src="<?=base_url('assets/img/metrics/12.png');?>" />
                            <h4>Net Profit Margin in %</h4>
                            <?php
                              if(isset($_GET['year']) && isset($_GET['month']))
                              {
                                $net_profit_margin = $this->db->get_where('net_profit_margin',array('month'=>$_GET['month'],'year'=>$_GET['year'],'startup_id'=>$startup->id,'status'=>1))->row();
                                echo "<h3> ".number_format($net_profit_margin->npm)."</h3>";
                              } 
                              else 
                              {
                                echo "NA";
                              }
                            ?>
                        </div>
                        <div class="card-footer">
                            <a href="#" class="btn btn-success"
                                onclick="showAjaxModal('<?=base_url(); ?>Popup/index/add-matrics/<?=$a=12;?>')"><i
                                    class="fa fa-plus"></i></a>
                            <a href="<?=base_url();?>StartupMetrics/GrossProfitMarginList" class="btn btn-warning">Gross
                                Profit Margin List</a>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </main>

    <?=include('common/footer.php');?>