<?=include('common/header.php');?>
<?=include('common/sidebar.php');?>
<div class="main">
    <?=include('common/topNav.php');?>
    <main class="content" style="z-index: 10">
        <div class="container-fluid">

            <div class="row">

                <div class="col-xl-12 col-xxl-12 d-flex">
                    <div class="w-100">
                        <div class="row mt-5">

                            <div class="col-md-3">
                                <div class="card">
                                    <div class="card-header bg-warning">
                                        <h3 class="text-center text-white">Monthly Recurring Revenue</h3>
                                    </div>
                                    <div class="card-body">

                                        <p>Monthly Recurring Revenue (MRR) is the predictable total revenue generated by
                                            your business from all the active subscriptions in a particular month. It
                                            includes recurring charges from discounts, coupons, and recurring add-ons,
                                            but excludes one-time fees.</p>
                                    </div>
                                    <div class="card-footer text-center">
                                        <a href="<?=base_url();?>StartupMatrix/MRR" class="btn btn-dark">Update</a>
                                    </div>
                                </div>

                            </div>
                            <div class="col-md-3">
                                <div class="card">
                                    <div class="card-header bg-warning">
                                        <h3 class="text-center text-white">Annual Recurring Revenue</h3>
                                    </div>
                                    <div class="card-body">

                                        <p>Annual recurring revenue (ARR) refers to all ongoing revenue for a product or
                                            business, projected over one year. Companies that offer yearly subscriptions
                                            use this metric to determine how much revenue they can expect each year.</p>
                                    </div>
                                    <div class="card-footer text-center">
                                        <a href="<?=base_url();?>StartupMatrix/ARR" class="btn btn-dark">Update</a>
                                    </div>
                                </div>

                            </div>
                            <div class="col-md-3">
                                <div class="card">
                                    <div class="card-header bg-warning">
                                        <h3 class="text-center text-white">Compounded Monthly Growth Rate (CMGR) </h3>
                                    </div>
                                    <div class="card-body">

                                        <p>Compounded Monthly Growth Rate (CMGR) is a calculation that helps investors
                                            measure the periodic growth on an investment over a certain period of time.
                                        </p>
                                    </div>
                                    <div class="card-footer text-center">
                                        <a href="<?=base_url();?>StartupMatrix/CMGR" class="btn btn-dark">Update</a>
                                    </div>
                                </div>

                            </div>
                            <div class="col-md-3">
                                <div class="card">
                                    <div class="card-header bg-warning">
                                        <h3 class="text-center text-white">Revenue ( Gross and Net)</h3>
                                    </div>
                                    <div class="card-body">

                                        <p>Gross revenue measures a company's total income from sales without returns or
                                            discounts. Net revenue, however, refers to the total amount of money that
                                            the company collected after adjusting for returns and allowances
                                        </p>
                                    </div>
                                    <div class="card-footer text-center">
                                        <a href="<?=base_url();?>StartupMatrix/Revenue" class="btn btn-dark">Update</a>
                                    </div>
                                </div>

                            </div>

                            <div class="col-md-3">
                                <div class="card">
                                    <div class="card-header bg-warning">
                                        <h3 class="text-center text-white">Average Revenue Per User</h3>
                                    </div>
                                    <div class="card-body">

                                        <p>Average revenue per user measures the amount of money that a company can
                                            expect to generate from an individual customer. It's Updated by dividing
                                            the business's total revenue by its total number of users</p>
                                    </div>
                                    <div class="card-footer text-center">
                                        <a href="<?=base_url();?>StartupMatrix/AverageRevenuePerUser"
                                            class="btn btn-dark">Update</a>
                                    </div>
                                </div>

                            </div>
                            <div class="col-md-3">
                                <div class="card">
                                    <div class="card-header bg-warning">
                                        <h3 class="text-center text-white">Customer Acquisition Cost</h3>
                                    </div>
                                    <div class="card-body">

                                        <p>Customer Acquisition Cost, or CAC, measures how much an organization spends
                                            to acquire new customers.</p>
                                    </div>
                                    <div class="card-footer text-center">
                                        <a href="<?=base_url();?>StartupMatrix/CustomerAcquisition"
                                            class="btn btn-dark">Update</a>
                                    </div>
                                </div>

                            </div>
                            <div class="col-md-3">
                                <div class="card">
                                    <div class="card-header bg-warning">
                                        <h3 class="text-center text-white">User Retention </h3>
                                    </div>
                                    <div class="card-body">

                                        <p>User retention is the continuing use of a product or feature. It's an
                                            important indicator for measuring the success of SaaS and digital products.
                                            It measures the percentage of first-time users who return in successive
                                            periods.
                                        </p>
                                    </div>
                                    <div class="card-footer text-center">
                                        <a href="<?=base_url();?>StartupMatrix/UserRetention"
                                            class="btn btn-dark">Update</a>
                                    </div>
                                </div>

                            </div>
                            <!-- <div class="col-md-3">
                                <div class="card">
                                    <div class="card-header bg-warning">
                                        <h3 class="text-center text-white">Profit Margin</h3>
                                    </div>
                                    <div class="card-body">

                                        <p>Gross revenue measures a company's total income from sales without returns or
                                            discounts. Net revenue, however, refers to the total amount of money that
                                            the company collected after adjusting for returns and allowances
                                        </p>
                                    </div>
                                    <div class="card-footer text-center">
                                        <a href="<?=base_url();?>StartupMatrix/ProfitMargin"
                                            class="btn btn-dark">Update</a>
                                    </div>
                                </div>

                            </div>

                            <div class="col-md-3">
                                <div class="card">
                                    <div class="card-header bg-warning">
                                        <h3 class="text-center text-white">Customer Lifetime Value</h3>
                                    </div>
                                    <div class="card-body">

                                        <p>Monthly Recurring Revenue (MRR) is the predictable total revenue generated by
                                            your business from all the active subscriptions in a particular month. It
                                            includes recurring charges from discounts, coupons, and recurring add-ons,
                                            but excludes one-time fees.</p>
                                    </div>
                                    <div class="card-footer text-center">
                                        <a href="<?=base_url();?>StartupMatrix/CustomerLifetimeValue"
                                            class="btn btn-dark">Update</a>
                                    </div>
                                </div>

                            </div>
                            <div class="col-md-3">
                                <div class="card">
                                    <div class="card-header bg-warning">
                                        <h3 class="text-center text-white">Churn Rate</h3>
                                    </div>
                                    <div class="card-body">

                                        <p>Annual recurring revenue (ARR) refers to all ongoing revenue for a product or
                                            business, projected over one year. Companies that offer yearly subscriptions
                                            use this metric to determine how much revenue they can expect each year.</p>
                                    </div>
                                    <div class="card-footer text-center">
                                        <a href="<?=base_url();?>StartupMatrix/ChurnRate"
                                            class="btn btn-dark">Update</a>
                                    </div>
                                </div>

                            </div>
                            <div class="col-md-3">
                                <div class="card">
                                    <div class="card-header bg-warning">
                                        <h3 class="text-center text-white">Cash Burn </h3>
                                    </div>
                                    <div class="card-body">

                                        <p>Compounded Monthly Growth Rate (CMGR) is a calculation that helps investors
                                            measure the periodic growth on an investment over a certain period of time.
                                        </p>
                                    </div>
                                    <div class="card-footer text-center">
                                        <a href="<?=base_url();?>StartupMatrix/CashBurn"
                                            class="btn btn-dark">Update</a>
                                    </div>
                                </div>

                            </div>
                            <div class="col-md-3">
                                <div class="card">
                                    <div class="card-header bg-warning">
                                        <h3 class="text-center text-white">Cash Runway</h3>
                                    </div>
                                    <div class="card-body">

                                        <p>Gross revenue measures a company's total income from sales without returns or
                                            discounts. Net revenue, however, refers to the total amount of money that
                                            the company collected after adjusting for returns and allowances
                                        </p>
                                    </div>
                                    <div class="card-footer text-center">
                                        <a href="<?=base_url();?>StartupMatrix/CashRunway"
                                            class="btn btn-dark">Update</a>
                                    </div>
                                </div>

                            </div> -->

                        </div>
                    </div>
                </div>
            </div>

        </div>
    </main>

    <?=include('common/footer.php');?>